services:
  - type: web
    name: usemytime
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd UseMyTime && python manage.py collectstatic --no-input && python manage.py migrate && gunicorn --bind 0.0.0.0:$PORT wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DB_ENGINE
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: usemytime-db
          property: connectionString
